//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.02 at 12:38:01 PM MSK 
//


package psyriccio.voteflow.api.jaxb.deputies.impl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import psyriccio.voteflow.api.jaxb.BaseObj;
import psyriccio.voteflow.api.jaxb.deputies.Deputy;
import psyriccio.voteflow.api.jaxb.deputies.Faction;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "name",
    "position",
    "isCurrent",
    "factions"
})
@XmlRootElement(name = "deputy")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class DeputyImpl
    extends BaseObj
    implements Deputy
{

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected BigInteger id;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String name;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String position;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected boolean isCurrent;
    @XmlElement(name = "faction", type = FactionImpl.class)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<Faction> factions;

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public BigInteger getId() {
        return id;
    }

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setId(BigInteger value) {
        this.id = value;
    }

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getName() {
        return name;
    }

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setName(String value) {
        this.name = value;
    }

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getPosition() {
        return position;
    }

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPosition(String value) {
        this.position = value;
    }

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isIsCurrent() {
        return isCurrent;
    }

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setIsCurrent(boolean value) {
        this.isCurrent = value;
    }

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:01+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<Faction> getFactions() {
        if (factions == null) {
            factions = new ArrayList<Faction>();
        }
        return this.factions;
    }

}
