//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.02 at 12:57:04 AM MSK 
//


package psyriccio.voteflow.api.jaxb.deputies.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import psyriccio.voteflow.api.jaxb.BaseObj;
import psyriccio.voteflow.api.jaxb.deputies.Deputy;
import psyriccio.voteflow.api.jaxb.deputies.Result;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deputies"
})
@XmlRootElement(name = "result")
public class ResultImpl
    extends BaseObj
    implements Result
{

    @XmlElement(name = "deputy", required = true, type = DeputyImpl.class)
    protected List<Deputy> deputies;

    public List<Deputy> getDeputies() {
        if (deputies == null) {
            deputies = new ArrayList<Deputy>();
        }
        return this.deputies;
    }

}
