//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.10.01 at 11:33:04 PM MSK
//


package psyriccio.voteflow.api.jaxb.votes;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import lombok.Data;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}id"/>
 *         &lt;element ref="{}subject"/>
 *         &lt;element ref="{}voteDate"/>
 *         &lt;element ref="{}voteCount"/>
 *         &lt;element ref="{}forCount"/>
 *         &lt;element ref="{}againstCount"/>
 *         &lt;element ref="{}abstainCount"/>
 *         &lt;element ref="{}absentCount"/>
 *         &lt;element ref="{}resultType"/>
 *         &lt;element ref="{}result"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "subject",
    "voteDate",
    "voteCount",
    "forCount",
    "againstCount",
    "abstainCount",
    "absentCount",
    "resultType",
    "result"
})
@XmlRootElement(name = "vote")
@Data
public class Vote {

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(required = true)
    protected String subject;
    @XmlElement(required = true)
    protected String voteDate;
    @XmlElement(required = true)
    protected BigInteger voteCount;
    @XmlElement(required = true)
    protected BigInteger forCount;
    @XmlElement(required = true)
    protected BigInteger againstCount;
    @XmlElement(required = true)
    protected BigInteger abstainCount;
    @XmlElement(required = true)
    protected BigInteger absentCount;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String resultType;
    @XmlElement(required = true)
    protected Result result;

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the subject property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the voteDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVoteDate() {
        return voteDate;
    }

    /**
     * Sets the value of the voteDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVoteDate(String value) {
        this.voteDate = value;
    }

    /**
     * Gets the value of the voteCount property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getVoteCount() {
        return voteCount;
    }

    /**
     * Sets the value of the voteCount property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setVoteCount(BigInteger value) {
        this.voteCount = value;
    }

    /**
     * Gets the value of the forCount property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getForCount() {
        return forCount;
    }

    /**
     * Sets the value of the forCount property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setForCount(BigInteger value) {
        this.forCount = value;
    }

    /**
     * Gets the value of the againstCount property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getAgainstCount() {
        return againstCount;
    }

    /**
     * Sets the value of the againstCount property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setAgainstCount(BigInteger value) {
        this.againstCount = value;
    }

    /**
     * Gets the value of the abstainCount property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getAbstainCount() {
        return abstainCount;
    }

    /**
     * Sets the value of the abstainCount property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setAbstainCount(BigInteger value) {
        this.abstainCount = value;
    }

    /**
     * Gets the value of the absentCount property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getAbsentCount() {
        return absentCount;
    }

    /**
     * Sets the value of the absentCount property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setAbsentCount(BigInteger value) {
        this.absentCount = value;
    }

    /**
     * Gets the value of the resultType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getResultType() {
        return resultType;
    }

    /**
     * Sets the value of the resultType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setResultType(String value) {
        this.resultType = value;
    }

    /**
     * Gets the value of the result property.
     *
     * @return
     *     possible object is
     *     {@link Result }
     *
     */
    public Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     *
     * @param value
     *     allowed object is
     *     {@link Result }
     *
     */
    public void setResult(Result value) {
        this.result = value;
    }

}
