//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.02 at 12:38:05 PM MSK 
//


package psyriccio.voteflow.api.jaxb.periods.impl;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import psyriccio.voteflow.api.jaxb.BaseObj;
import psyriccio.voteflow.api.jaxb.periods.Period;
import psyriccio.voteflow.api.jaxb.periods.Result;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "periods"
})
@XmlRootElement(name = "result")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:05+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class ResultImpl
    extends BaseObj
    implements Result
{

    @XmlElement(name = "period", required = true, type = PeriodImpl.class)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:05+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<Period> periods;

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-02T12:38:05+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<Period> getPeriods() {
        if (periods == null) {
            periods = new ArrayList<Period>();
        }
        return this.periods;
    }

}
