//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.02 at 12:57:07 AM MSK 
//


package psyriccio.voteflow.api.jaxb.votes.impl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import psyriccio.voteflow.api.jaxb.BaseObj;
import psyriccio.voteflow.api.jaxb.votes.Result;
import psyriccio.voteflow.api.jaxb.votes.Vote;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "subject",
    "voteDate",
    "voteCount",
    "forCount",
    "againstCount",
    "abstainCount",
    "absentCount",
    "resultType",
    "result"
})
@XmlRootElement(name = "vote")
public class VoteImpl
    extends BaseObj
    implements Vote
{

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(required = true)
    protected String subject;
    @XmlElement(required = true)
    protected String voteDate;
    @XmlElement(required = true)
    protected BigInteger voteCount;
    @XmlElement(required = true)
    protected BigInteger forCount;
    @XmlElement(required = true)
    protected BigInteger againstCount;
    @XmlElement(required = true)
    protected BigInteger abstainCount;
    @XmlElement(required = true)
    protected BigInteger absentCount;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String resultType;
    @XmlElement(required = true, type = ResultImpl.class)
    protected ResultImpl result;

    public BigInteger getId() {
        return id;
    }

    public void setId(BigInteger value) {
        this.id = value;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String value) {
        this.subject = value;
    }

    public String getVoteDate() {
        return voteDate;
    }

    public void setVoteDate(String value) {
        this.voteDate = value;
    }

    public BigInteger getVoteCount() {
        return voteCount;
    }

    public void setVoteCount(BigInteger value) {
        this.voteCount = value;
    }

    public BigInteger getForCount() {
        return forCount;
    }

    public void setForCount(BigInteger value) {
        this.forCount = value;
    }

    public BigInteger getAgainstCount() {
        return againstCount;
    }

    public void setAgainstCount(BigInteger value) {
        this.againstCount = value;
    }

    public BigInteger getAbstainCount() {
        return abstainCount;
    }

    public void setAbstainCount(BigInteger value) {
        this.abstainCount = value;
    }

    public BigInteger getAbsentCount() {
        return absentCount;
    }

    public void setAbsentCount(BigInteger value) {
        this.absentCount = value;
    }

    public String getResultType() {
        return resultType;
    }

    public void setResultType(String value) {
        this.resultType = value;
    }

    public Result getResult() {
        return result;
    }

    public void setResult(Result value) {
        this.result = ((ResultImpl) value);
    }

}
