//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.02 at 12:57:06 AM MSK 
//


package psyriccio.voteflow.api.jaxb.stages.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import psyriccio.voteflow.api.jaxb.BaseObj;
import psyriccio.voteflow.api.jaxb.stages.Result;
import psyriccio.voteflow.api.jaxb.stages.Stage;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stages"
})
@XmlRootElement(name = "result")
public class ResultImpl
    extends BaseObj
    implements Result
{

    @XmlElement(name = "stage", required = true, type = StageImpl.class)
    protected List<Stage> stages;

    public List<Stage> getStages() {
        if (stages == null) {
            stages = new ArrayList<Stage>();
        }
        return this.stages;
    }

}
