//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.02 at 10:27:16 PM MSK 
//


package psyriccio.voteflow.api.jaxb.stages.impl;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import psyriccio.voteflow.api.jaxb.BaseObj;
import psyriccio.voteflow.api.jaxb.stages.Result;
import psyriccio.voteflow.api.jaxb.stages.Stage;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stages"
})
@XmlRootElement(name = "result")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2016-10-02T10:27:16+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.2-147")
public class ResultImpl
    extends BaseObj
    implements Result
{

    @XmlElement(name = "stage", required = true, type = StageImpl.class)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-10-02T10:27:16+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.2-147")
    protected List<Stage> stages;

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-10-02T10:27:16+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.2-147")
    public List<Stage> getStages() {
        if (stages == null) {
            stages = new ArrayList<Stage>();
        }
        return this.stages;
    }

}
