//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.02 at 12:57:06 AM MSK 
//


package psyriccio.voteflow.api.jaxb.stages.impl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import psyriccio.voteflow.api.jaxb.BaseObj;
import psyriccio.voteflow.api.jaxb.stages.Phase;
import psyriccio.voteflow.api.jaxb.stages.Stage;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "name",
    "phases"
})
@XmlRootElement(name = "stage")
public class StageImpl
    extends BaseObj
    implements Stage
{

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "phase", required = true, type = PhaseImpl.class)
    protected List<Phase> phases;

    public BigInteger getId() {
        return id;
    }

    public void setId(BigInteger value) {
        this.id = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public List<Phase> getPhases() {
        if (phases == null) {
            phases = new ArrayList<Phase>();
        }
        return this.phases;
    }

}
