//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.02 at 10:27:12 PM MSK 
//


package psyriccio.voteflow.api.jaxb.topics.impl;

import java.math.BigInteger;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import psyriccio.voteflow.api.jaxb.BaseObj;
import psyriccio.voteflow.api.jaxb.topics.Topic;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "name"
})
@XmlRootElement(name = "topic")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2016-10-02T10:27:12+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.2-147")
public class TopicImpl
    extends BaseObj
    implements Topic
{

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-10-02T10:27:12+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.2-147")
    protected BigInteger id;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-10-02T10:27:12+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.2-147")
    protected String name;

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-10-02T10:27:12+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.2-147")
    public BigInteger getId() {
        return id;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-10-02T10:27:12+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.2-147")
    public void setId(BigInteger value) {
        this.id = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-10-02T10:27:12+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.2-147")
    public String getName() {
        return name;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-10-02T10:27:12+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.2-147")
    public void setName(String value) {
        this.name = value;
    }

}
